### PR TITLE
update: autocompletion icons

### PR DESCRIPTION
**Pull request by buttercubz**

### CODE REVIEW

**Comment by marc2332** [comment]
They look very nice! You made them?

**Comment by buttercubz** [comment]
> They look very nice! You made them?

oh, I wish I could make them myself, I always use svg from [flaticon](https://www.flaticon.es/) since they are the vast majority of open source

**Comment by marc2332** [comment]
So, they can be used in open source projects directly? Do they need some kind of attribution? 

I just wanna be sure

**Comment by buttercubz** [comment]
> So, they can be used in open source projects directly? Do they need some kind of attribution?
> 
> I just wanna be sure


yes, you just have to put this in the readme.

<div>Iconos diseñados por <a href="https://www.flaticon.es/autores/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/" title="Flaticon">www.flaticon.es</a></div>

**Comment by marc2332** [comment]
Well, I think it would be better to have our own icons since I wanna make their's color customizable, I might need to modify them to do so

🙏 Sorry

**Comment by buttercubz** [comment]
No problem, I think it is good that they can be personalized, I close this pr?

**Pull request closed without merging**
